spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
welcome:
  message: I am from properties file!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
